# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: wfung <marvin@42.fr>                       +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2016/11/14 12:26:29 by wfung             #+#    #+#              #
#    Updated: 2016/11/14 12:31:17 by wfung            ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

CC = gcc

CFLAGS = -Wall -Wextra -Werror

NAME = 

SRCS = 

INCL = 

OBJS = 

all: $(NAME)

$(NAME):
	$(CC) $(CFLAGS) -c $(SRCS)
	ar rc $(OBJS) -o $(NAME)

clean:
	bin/r, -f $(OBJS)

fclean: clean
		/bin/rm -f $(NAME)

re: fclean all
